version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env.local
    environment:
      - REDIS_DOMAIN=redis
      - MONGO_BASE_URI=mongo
    depends_on:
      - mongo

  tntra_node:
    container_name: bootcamp_app
    image: tntra-nodejs-bootcamp_app
    ports:
      - "9080:9000"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    depends_on:
      - mongo
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
